<?php
/**
 * CallTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CallTest Class Doc Comment
 *
 * @category    Class */
// * @description Call
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CallTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Call"
     */
    public function testCall()
    {
    }

    /**
     * Test attribute "access_token"
     */
    public function testPropertyAccessToken()
    {
    }

    /**
     * Test attribute "access_token_owner"
     */
    public function testPropertyAccessTokenOwner()
    {
    }

    /**
     * Test attribute "additional_data"
     */
    public function testPropertyAdditionalData()
    {
    }

    /**
     * Test attribute "api_component_type"
     */
    public function testPropertyApiComponentType()
    {
    }

    /**
     * Test attribute "api_id"
     */
    public function testPropertyApiId()
    {
    }

    /**
     * Test attribute "api_name"
     */
    public function testPropertyApiName()
    {
    }

    /**
     * Test attribute "app_developer"
     */
    public function testPropertyAppDeveloper()
    {
    }

    /**
     * Test attribute "app_name"
     */
    public function testPropertyAppName()
    {
    }

    /**
     * Test attribute "app_token"
     */
    public function testPropertyAppToken()
    {
    }

    /**
     * Test attribute "auth_owner"
     */
    public function testPropertyAuthOwner()
    {
    }

    /**
     * Test attribute "base_url"
     */
    public function testPropertyBaseUrl()
    {
    }

    /**
     * Test attribute "billing"
     */
    public function testPropertyBilling()
    {
    }

    /**
     * Test attribute "cache"
     */
    public function testPropertyCache()
    {
    }

    /**
     * Test attribute "call_date"
     */
    public function testPropertyCallDate()
    {
    }

    /**
     * Test attribute "caller_address"
     */
    public function testPropertyCallerAddress()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "complete_url"
     */
    public function testPropertyCompleteUrl()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "duration_millis"
     */
    public function testPropertyDurationMillis()
    {
    }

    /**
     * Test attribute "environment_id"
     */
    public function testPropertyEnvironmentId()
    {
    }

    /**
     * Test attribute "environment_name"
     */
    public function testPropertyEnvironmentName()
    {
    }

    /**
     * Test attribute "gateway_duration_millis"
     */
    public function testPropertyGatewayDurationMillis()
    {
    }

    /**
     * Test attribute "http_status"
     */
    public function testPropertyHttpStatus()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "inserted_on_date"
     */
    public function testPropertyInsertedOnDate()
    {
    }

    /**
     * Test attribute "method"
     */
    public function testPropertyMethod()
    {
    }

    /**
     * Test attribute "operation_id"
     */
    public function testPropertyOperationId()
    {
    }

    /**
     * Test attribute "operation_name"
     */
    public function testPropertyOperationName()
    {
    }

    /**
     * Test attribute "received_from_address"
     */
    public function testPropertyReceivedFromAddress()
    {
    }

    /**
     * Test attribute "received_on"
     */
    public function testPropertyReceivedOn()
    {
    }

    /**
     * Test attribute "received_on_date"
     */
    public function testPropertyReceivedOnDate()
    {
    }

    /**
     * Test attribute "redis"
     */
    public function testPropertyRedis()
    {
    }

    /**
     * Test attribute "request_headers"
     */
    public function testPropertyRequestHeaders()
    {
    }

    /**
     * Test attribute "request_id"
     */
    public function testPropertyRequestId()
    {
    }

    /**
     * Test attribute "request_payload"
     */
    public function testPropertyRequestPayload()
    {
    }

    /**
     * Test attribute "resource_id"
     */
    public function testPropertyResourceId()
    {
    }

    /**
     * Test attribute "resource_name"
     */
    public function testPropertyResourceName()
    {
    }

    /**
     * Test attribute "response_headers"
     */
    public function testPropertyResponseHeaders()
    {
    }

    /**
     * Test attribute "response_payload"
     */
    public function testPropertyResponsePayload()
    {
    }

    /**
     * Test attribute "result_status"
     */
    public function testPropertyResultStatus()
    {
    }

    /**
     * Test attribute "revision_id"
     */
    public function testPropertyRevisionId()
    {
    }

    /**
     * Test attribute "trace"
     */
    public function testPropertyTrace()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "type_error"
     */
    public function testPropertyTypeError()
    {
    }

    /**
     * Test attribute "type_status"
     */
    public function testPropertyTypeStatus()
    {
    }

    /**
     * Test attribute "uri"
     */
    public function testPropertyUri()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "year_month"
     */
    public function testPropertyYearMonth()
    {
    }
}
