<?php
/**
 * DeploymentBeanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DeploymentBeanTest Class Doc Comment
 *
 * @category    Class */
// * @description DeploymentBean
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DeploymentBeanTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DeploymentBean"
     */
    public function testDeploymentBean()
    {
    }

    /**
     * Test attribute "api_description"
     */
    public function testPropertyApiDescription()
    {
    }

    /**
     * Test attribute "api_id"
     */
    public function testPropertyApiId()
    {
    }

    /**
     * Test attribute "api_name"
     */
    public function testPropertyApiName()
    {
    }

    /**
     * Test attribute "deploy_date"
     */
    public function testPropertyDeployDate()
    {
    }

    /**
     * Test attribute "deployment_schedule"
     */
    public function testPropertyDeploymentSchedule()
    {
    }

    /**
     * Test attribute "environment_id"
     */
    public function testPropertyEnvironmentId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "revision_id"
     */
    public function testPropertyRevisionId()
    {
    }

    /**
     * Test attribute "revision_number"
     */
    public function testPropertyRevisionNumber()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
