<?php
/**
 * RevisionBeanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RevisionBeanTest Class Doc Comment
 *
 * @category    Class */
// * @description RevisionBean
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RevisionBeanTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RevisionBean"
     */
    public function testRevisionBean()
    {
    }

    /**
     * Test attribute "api"
     */
    public function testPropertyApi()
    {
    }

    /**
     * Test attribute "api_broken"
     */
    public function testPropertyApiBroken()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "deployments"
     */
    public function testPropertyDeployments()
    {
    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "interceptors"
     */
    public function testPropertyInterceptors()
    {
    }

    /**
     * Test attribute "life_cycle"
     */
    public function testPropertyLifeCycle()
    {
    }

    /**
     * Test attribute "resources"
     */
    public function testPropertyResources()
    {
    }

    /**
     * Test attribute "revision_number"
     */
    public function testPropertyRevisionNumber()
    {
    }

    /**
     * Test attribute "timeout"
     */
    public function testPropertyTimeout()
    {
    }
}
