<?php
/**
 * APIsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * APIsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class APIsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cloneApi1
     *
     * Clone a API.
     *
     */
    public function testCloneApi1()
    {
    }

    /**
     * Test case for createApi1
     *
     * Create a new API.
     *
     */
    public function testCreateApi1()
    {
    }

    /**
     * Test case for createNewVersion1
     *
     * Create new version.
     *
     */
    public function testCreateNewVersion1()
    {
    }

    /**
     * Test case for getApiById1
     *
     * Find API by id.
     *
     */
    public function testGetApiById1()
    {
    }

    /**
     * Test case for getApis1
     *
     * Return all APIs.
     *
     */
    public function testGetApis1()
    {
    }

    /**
     * Test case for getChangeLogByApiId1
     *
     * Retrive changelog per API id.
     *
     */
    public function testGetChangeLogByApiId1()
    {
    }

    /**
     * Test case for getLastRevisionByApi1
     *
     * Find last revision by API id.
     *
     */
    public function testGetLastRevisionByApi1()
    {
    }

    /**
     * Test case for getVersionsByApi1
     *
     * Find version by API id.
     *
     */
    public function testGetVersionsByApi1()
    {
    }

    /**
     * Test case for removeApi1
     *
     * Delete a API.
     *
     */
    public function testRemoveApi1()
    {
    }

    /**
     * Test case for removeLinkEnvironmentWithApi1
     *
     * Delete environment link with API.
     *
     */
    public function testRemoveLinkEnvironmentWithApi1()
    {
    }

    /**
     * Test case for updateApi1
     *
     * Update a API.
     *
     */
    public function testUpdateApi1()
    {
    }

    /**
     * Test case for validatePartialApi1
     *
     * Validate partial a API.
     *
     */
    public function testValidatePartialApi1()
    {
    }
}
