<?php
/**
 * DevelopersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DevelopersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DevelopersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrUpdateDeveloper1
     *
     * Create or update developer.
     *
     */
    public function testCreateOrUpdateDeveloper1()
    {
    }

    /**
     * Test case for developersCount1
     *
     * Retrieve developers total.
     *
     */
    public function testDevelopersCount1()
    {
    }

    /**
     * Test case for removeDeveloper1
     *
     * Delete developer.
     *
     */
    public function testRemoveDeveloper1()
    {
    }

    /**
     * Test case for retriveChangeLogByUsername1
     *
     * Retrive audit developer per username.
     *
     */
    public function testRetriveChangeLogByUsername1()
    {
    }

    /**
     * Test case for retriveDeveloperByLogin1
     *
     * Retrive developer per Login.
     *
     */
    public function testRetriveDeveloperByLogin1()
    {
    }

    /**
     * Test case for retriveDevelopers1
     *
     * Retrive developers.
     *
     */
    public function testRetriveDevelopers1()
    {
    }
}
