<?php
/**
 * MetricsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MetricsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MetricsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getAccessTokensByMonth1
     *
     * Find access token consolited by month.
     *
     */
    public function testGetAccessTokensByMonth1()
    {
    }

    /**
     * Test case for getAppsByMonth1
     *
     * Find apps consolited by month.
     *
     */
    public function testGetAppsByMonth1()
    {
    }

    /**
     * Test case for getCache1
     *
     * Find cache.
     *
     */
    public function testGetCache1()
    {
    }

    /**
     * Test case for getCacheLatency1
     *
     * Find cache latency.
     *
     */
    public function testGetCacheLatency1()
    {
    }

    /**
     * Test case for getCacheSize1
     *
     * Retrive cache size.
     *
     */
    public function testGetCacheSize1()
    {
    }

    /**
     * Test case for getCallsByMonth1
     *
     * Find calls by month.
     *
     */
    public function testGetCallsByMonth1()
    {
    }

    /**
     * Test case for getHealth1
     *
     * Find Health.
     *
     */
    public function testGetHealth1()
    {
    }

    /**
     * Test case for getLatencyByMonth1
     *
     * Find latency by month.
     *
     */
    public function testGetLatencyByMonth1()
    {
    }

    /**
     * Test case for getStatusError1
     *
     * Retrive Status Error.
     *
     */
    public function testGetStatusError1()
    {
    }

    /**
     * Test case for getTopAccessTokens1
     *
     * Find top access token.
     *
     */
    public function testGetTopAccessTokens1()
    {
    }

    /**
     * Test case for getTopApps1
     *
     * Find top apps.
     *
     */
    public function testGetTopApps1()
    {
    }
}
