<?php
/**
 * PlansApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PlansApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PlansApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for clonePlan1
     *
     * Clone a plan.
     *
     */
    public function testClonePlan1()
    {
    }

    /**
     * Test case for createPlan1
     *
     * Create a new plan.
     *
     */
    public function testCreatePlan1()
    {
    }

    /**
     * Test case for getAllPlan1
     *
     * Return all plan.
     *
     */
    public function testGetAllPlan1()
    {
    }

    /**
     * Test case for getChangeLogByPlanId1
     *
     * Retrive changelog per plan id.
     *
     */
    public function testGetChangeLogByPlanId1()
    {
    }

    /**
     * Test case for getPlanById1
     *
     * Find plan by id.
     *
     */
    public function testGetPlanById1()
    {
    }

    /**
     * Test case for getPlanDefaultByApiId1
     *
     * Find default plan by api id.
     *
     */
    public function testGetPlanDefaultByApiId1()
    {
    }

    /**
     * Test case for plansCount1
     *
     * Retrieve plan total.
     *
     */
    public function testPlansCount1()
    {
    }

    /**
     * Test case for removePlan1
     *
     * Delete a plan.
     *
     */
    public function testRemovePlan1()
    {
    }

    /**
     * Test case for updatePlan1
     *
     * Update a plan.
     *
     */
    public function testUpdatePlan1()
    {
    }

    /**
     * Test case for validatePartialPlan1
     *
     * Validate partial a plan.
     *
     */
    public function testValidatePartialPlan1()
    {
    }
}
